# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rabougue <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/01/06 12:01:50 by rabougue          #+#    #+#              #
#    Updated: 2016/01/21 10:37:59 by rabougue         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FLAG = -Wall -Werror -Wextra

NAME = fillit

SRCS_PATH = ./source/

SRCS = $(addprefix $(SRCS_PATH), $(SRCS_NAME))

OBJS = $(SRCS_NAME:.c=.o)

HEAD = ./headers/

LIBFT = headers/libft.a

SRCS_NAME = check_tetriminos.c \
			check_un.c \
			check_un_2.c \
			check_un_3.c \
			check_un_4.c \
			caclul_coordonee.c \
			check_map.c \
			check_map_2.c \
			check_last_rc.c \
			ft_openfile.c \
			backtracking.c \
			creat_tab.c \
			stock_coord.c \
			stock_coord_j.c \
			stock_coord_l.c \
			stock_coord_o.c \
			stock_coord_s.c \
			stock_coord_z.c \
			stock_coord_i.c \
			stock_coord_t.c \
			main.c

all: $(NAME)

$(NAME):
	@gcc $(FLAG) -c $(SRCS) -I $(HEAD)
	@gcc -o $(NAME) $(OBJS) $(LIBFT)
	@echo "\033[31mCompiled !\033[0m"

clean:
	@rm -f $(OBJS)
	@echo "\033[31mDeleting all .o ...\033[0m"

mc: all clean

fclean: clean
	@echo "\033[31mDeleting fillit ...\033[0m"
	@echo "\033[32mThe folder is clean\033[0m"
	@rm -f $(NAME)

re: fclean all

tetris:
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |   \033[36m####\033[0m   | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |          |    0   |   | |"
	@echo "| |    |__|__________|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |   \033[36m####\033[0m   |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |          |    0   |   | |"
	@echo "| |    |__|__________|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |   \033[36m####\033[0m   | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |          |    0   |   | |"
	@echo "| |    |__|__________|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |   \033[36m####\033[0m   |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |          |    0   |   | |"
	@echo "| |    |__|__________|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |   \033[36m####\033[0m   |  LINE  |   | |"
	@echo "| |    |  |          |    0   |   | |"
	@echo "| |    |__|__________|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |   \033[36m####\033[0m   |    0   |   | |"
	@echo "| |    |__|__________|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |          |    0   |   | |"
	@echo "| |    |__|___\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |   \033[35m###\033[0m    | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |          |    0   |   | |"
	@echo "| |    |__|___\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |   \033[35m # \033[0m    | SCORE  |   | |"
	@echo "| | o  |  |   \033[35m###\033[0m    |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |          |    0   |   | |"
	@echo "| |    |__|___\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |   \033[35m # \033[0m    |   0    |   | |"
	@echo "| |    |  |   \033[35m###\033[0m    | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |          |    0   |   | |"
	@echo "| |    |__|___\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |   \033[35m # \033[0m    | LEVEL  |   | |"
	@echo "| |    |  |   \033[35m###\033[0m    |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |          |    0   |   | |"
	@echo "| |    |__|___\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |   \033[35m # \033[0m    |   1    |   | |"
	@echo "| |    |  |   \033[35m###\033[0m    |  LINE  |   | |"
	@echo "| |    |  |          |    0   |   | |"
	@echo "| |    |__|___\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |   \033[35m # \033[0m    |  LINE  |   | |"
	@echo "| |    |  |   \033[35m###\033[0m    |    0   |   | |"
	@echo "| |    |__|___\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |  \033[35m # \033[0m     |  LINE  |   | |"
	@echo "| |    |  |  \033[35m###\033[0m     |    0   |   | |"
	@echo "| |    |__|___\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  | \033[35m # \033[0m      |  LINE  |   | |"
	@echo "| |    |  | \033[35m###\033[0m      |    0   |   | |"
	@echo "| |    |__|___\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |\033[35m # \033[0m       |  LINE  |   | |"
	@echo "| |    |  |\033[35m###\033[0m       |    0   |   | |"
	@echo "| |    |__|___\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m       |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |   \033[1;33m##\033[0m     | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m       |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |   \033[1;33m##\033[0m     | SCORE  |   | |"
	@echo "| | o  |  |   \033[1;33m##\033[0m     |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m       |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |   \033[1;33m##\033[0m     |   0    |   | |"
	@echo "| |    |  |   \033[1;33m##\033[0m     | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m       |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |   \033[1;33m##\033[0m     | LEVEL  |   | |"
	@echo "| |    |  |   \033[1;33m##\033[0m     |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m       |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |   \033[1;33m##\033[0m     |   1    |   | |"
	@echo "| |    |  |   \033[1;33m##\033[0m     |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m       |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |   \033[1;33m##\033[0m     |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m\033[1;33m##\033[0m     |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |    \033[1;33m##\033[0m    |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m \033[1;33m##\033[0m    |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |     \033[1;33m##\033[0m   |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m  \033[1;33m##\033[0m   |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |      \033[1;33m##\033[0m  |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m   \033[1;33m##\033[0m  |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |       \033[1;33m##\033[0m |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m___|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m\033[1;33m##\033[0m_|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |   \033[31m##\033[0m     | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m\033[1;33m##\033[0m_|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |   \033[31m#\033[0m      | SCORE  |   | |"
	@echo "| | o  |  |   \033[31m##\033[0m     |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m\033[1;33m##\033[0m_|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |   \033[31m#\033[0m      | SCORE  |   | |"
	@echo "| | o  |  |   \033[31m#\033[0m      |   0    |   | |"
	@echo "| |    |  |   \033[31m##\033[0m     | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m\033[1;33m##\033[0m_|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |   \033[31m#\033[0m      |   0    |   | |"
	@echo "| |    |  |   \033[31m#\033[0m      | LEVEL  |   | |"
	@echo "| |    |  |   \033[31m##\033[0m     |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m\033[1;33m##\033[0m_|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |   \033[31m#\033[0m      | LEVEL  |   | |"
	@echo "| |    |  |   \033[31m#\033[0m      |   1    |   | |"
	@echo "| |    |  |   \033[31m##\033[0m     |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m\033[1;33m##\033[0m_|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |   \033[31m###\033[0m    |   1    |   | |"
	@echo "| |    |  |   \033[31m#\033[0m      |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m\033[1;33m##\033[0m_|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |    \033[31m##\033[0m    | LEVEL  |   | |"
	@echo "| |    |  |     \033[31m#\033[0m    |   1    |   | |"
	@echo "| |    |  |     \033[31m#\033[0m    |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m\033[1;33m##\033[0m_|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |     \033[31m##\033[0m   | LEVEL  |   | |"
	@echo "| |    |  |      \033[31m#\033[0m   |   1    |   | |"
	@echo "| |    |  |      \033[31m#\033[0m   |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m\033[1;33m##\033[0m_|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |      \033[31m##\033[0m  | LEVEL  |   | |"
	@echo "| |    |  |       \033[31m#\033[0m  |   1    |   | |"
	@echo "| |    |  |       \033[31m#\033[0m  |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m\033[1;33m##\033[0m_|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |       \033[31m##\033[0m | LEVEL  |   | |"
	@echo "| |    |  |        \033[31m#\033[0m |   1    |   | |"
	@echo "| |    |  |        \033[31m#\033[0m |  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m\033[1;33m##\033[0m_|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |        \033[31m##\033[0m| LEVEL  |   | |"
	@echo "| |    |  |         \033[31m#\033[0m|   1    |   | |"
	@echo "| |    |  |         \033[31m#\033[0m|  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m |    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m\033[1;33m##\033[0m_|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |        \033[31m##\033[0m|  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m\033[31m#\033[0m|    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m\033[1;33m##\033[0m\033[31m#\033[0m|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   0    |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |        \033[31m##\033[0m|  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m\033[31m#\033[0m|    0   |   | |"
	@echo "| |    |__|\033[35m###\033[0m\033[36m####\033[0m\033[1;33m##\033[0m\033[31m#\033[0m|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   10   |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |        \033[31m##\033[0m|  LINE  |   | |"
	@echo "| |    |  |\033[35m # \033[0m    \033[1;33m##\033[0m\033[31m#\033[0m|    1   |   | |"
	@echo "| |    |__|__________|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@sleep 0.1
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   10   |   | |"
	@echo "| |    |  |          | LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |          |  LINE  |   | |"
	@echo "| |    |  |        \033[31m##\033[0m|    1   |   | |"
	@echo "| |    |__|\033[35m_#_\033[0m____\033[1;33m##\033[0m\033[31m#\033[0m|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
	@clear
	@echo " ___________________________________"
	@echo "|_|_<off-on>______________________|_|"
	@echo "|  _________________________________|"
	@echo "| | DOT MATRIX WITH STEREO SOUND  | |"
	@echo "| |     ______________________    | |"
	@echo "| |    |  |          | SCORE  |   | |"
	@echo "| | o  |  |          |   10   |   | |"
	@echo "| |    |  | \033[32mFinish ! \033[0m| LEVEL  |   | |"
	@echo "| |    |  |          |   1    |   | |"
	@echo "| |    |  |    \033[32m:)\033[0m    |  LINE  |   | |"
	@echo "| |    |  |        \033[31m##\033[0m|    1   |   | |"
	@echo "| |    |__|\033[35m_#_\033[0m____\033[1;33m##\033[0m\033[31m#\033[0m|________|   | |"
	@echo "| |                               | |"
	@echo "| |_______________________________| |"
	@echo "|  Nintendo GAME BOY™               |"
	@echo "|       _                           |"
	@echo "|     _| |_                      ◯  |"
	@echo "|    |_   _|                  ◯   A |"
	@echo "|      |_|                     B    |"
	@echo "|                                   |"
	@echo "|          ___    ___               |"
	@echo "|         start  selct      \ \     |"
	@echo "|                          \ \ \    |"
	@echo "|                         \ \ \     |"
	@echo "|                          \ \      |"
	@echo "|___________________________________|"
